### ISSUE TITLE
Part 0 doc update

### ISSUE THREAD

**Issue by aldelar** [microsoft/MLOpsTemplate#210]
https://github.com/microsoft/MLOpsTemplate/blob/main/src/workshop/documents/part_0.md

Things to improve:
- explain why we're launching CloudShell
- OR:
- NICE TO HAVE: use a 'deploy to azure' button in the repo based on ARM to just deploy with one click
- NICE TO HAVE: could we avoid cloning the repo and execute this script remotely: https://raw.githubusercontent.com/microsoft/MLOpsTemplate/main/src/workshop/documents/IaC/iac_mlopsworkshop.azcli
- indicate that the CloudShell should be closed once the script ran properly
- Have a checkpoint after the infra script ran to have user check that the infra is in place (go to portal manually, find workspace, check CI, CC, etc.

Section 3.:
- 'Merge instructions' for Option A and B
- add install instructions for conda / python etc.

**Comment by aldelar** [comment]
Document Azure Service Principal doc (move doc from CD section & Part 3 to Section 0)
Document setup GitHub secret setup with ServicePrincipal (AZURE_CREDS  + Personal Token for pull request)

**Comment by hyssh** [comment]
@aldelar, part 0 is updated. 

The CloudShell is removed and replaced by ARM template. Because of this creating SP part of section 3 in part 0.

**Comment by aldelar** [comment]
this seems to have been all addressed
