### ISSUE TITLE
Configuration items in a single location vs in all files

### ISSUE THREAD

**Issue by aldelar** [microsoft/MLOpsTemplate#235]
Compute name / resource name, etc...
Single place to setup their variables

**Comment by aldelar** [comment]
We would probably then get rid of all the my_*.yml files if we can centralize things to a single config file.

**Comment by james-tn** [comment]
Then just modify the config file then the rest is just to run everything?

**Comment by james-tn** [comment]
I think we can do that as part of the custom action
