### ISSUE TITLE
Remove all my_* files and use a #setup comment tag next to each param to change

### ISSUE THREAD

**Issue by aldelar** [microsoft/MLOpsTemplate#238]
Move all of the doc for custom config into Step 0 from all existing sections

Mention each file that needs to change in each section:

endpoint.yml:
- look for #setup and specify your own unique endpoint name

**Comment by james-tn** [comment]
done for part 1,2.

**Comment by fkhoshouei** [comment]
done for part 4

**Comment by nicoleserafino** [comment]
done for part 3

**Comment by aldelar** [comment]
done for part 5
