### ISSUE TITLE
Consistent Format for each section (reference format)

### ISSUE THREAD

**Issue by aldelar** [microsoft/MLOpsTemplate#241]
**Pre-requisites**
section X, where you accomplished the following:
- a)
- b)
- c)

**Summary**: what you will accomplish by the end of the section

**Steps**:

1) 'Explanation' / What/why: we separated feature engineering into its own piece of code
so that a data engineer could work on this independently from DS

How:
- feature_engineering.py
- yml: this is how you describe the job to the AML plafrom

Action Item: run the job / Color coded

2) 

...

5)

Completion Criteria / what you just learned / accomplished:

Back to Section X-1
To Section X+1

**Comment by james-tn** [comment]
done for part 1, 2

**Comment by nicoleserafino** [comment]
done for part 3

**Comment by aldelar** [comment]
done for part 5

**Comment by aldelar** [comment]
Closing this one as the core is done, and follow ups are in a different issue.
