### ISSUE TITLE
Integrate PowerPoint doc into the README (top level) and each section 'summary'

### ISSUE THREAD

**Issue by aldelar** [microsoft/MLOpsTemplate#242]

**Comment by aldelar** [comment]
Need to actually describe the use case as well

**Comment by thomassantosh** [comment]
First iteration: https://github.com/microsoft/MLOpsTemplate/blob/thomassantosh-dev/src/workshop/README.md (branch: thomassantosh-dev)

**Comment by thomassantosh** [comment]
Worked with Jared to close this off, new README here: https://github.com/microsoft/MLOpsTemplate/blob/main/src/workshop/README.md#workshop-scenario
