### ISSUE TITLE
GitHub setup: change secret names to be more representative of what they store

### ISSUE THREAD

**Issue by aldelar** [microsoft/MLOpsTemplate#343]

**Comment by aldelar** [comment]
Some confusion observed by workshop attendees down in later parts as they forgot which secret was what. Should name that more explicitely.

**Comment by aldelar** [comment]
AZURE_CREDENTIALS_USERNAME => AZURE_SERVICE_PRINCIPAL
USER_NAME_GITHUB_SECRET => GITHUB_PERSONAL_ACCESS_TOKEN

**Comment by aldelar** [comment]
Need to go across the docs + yml files to replace these occurences to have more descriptive secret names.

**Comment by nicoleserafino** [comment]
Secret names changes: #350
