### ISSUE TITLE
Remove need to replace CC name in yml files and document instead using specific CC name in setup

### ISSUE THREAD

**Issue by aldelar** [microsoft/MLOpsTemplate#346]
Ex:
https://github.com/microsoft/MLOpsTemplate/blob/main/src/workshop/core/data_engineering/feature_engineering.yml => shouldn't ask to replace 'DS11' but should use something like cpu-cluster.

+ Part-0 doc needs to cover defining a cluster named 'cpu-cluster'.

Update all necessary yml files to reflect that.

**Comment by james-tn** [comment]
updated
